#pragma once

#include <gmpxx.h>

#include <cassert>
#include <random>

namespace DG {
namespace Crypto {
class RandomInteger {
  // RandomInteger is a random number of size k bits
  // the value is generated by gmp
 public:
  // disable default constructor
  RandomInteger() = delete;
  // create random integer with ~k bits, use default random algorithm (marsenne
  // twister)
  RandomInteger(mp_bitcnt_t k)
      : bits_{k}, value_{0}, gmp_rand_alg_{gmp_randinit_default} {
    // seed gmp_rand_alg_ with a uint from random_device
    gmp_rand_alg_.seed(std::random_device{}());
    // set value
    value_ = generate_integer(k);
  }

  // get number of bits
  mp_bitcnt_t bits() const { return bits_; }
  // get value
  mpz_class value() const { return value_; }

 protected:
  //// private member variables
  // number of bits (mp_bitcnt_t is an unsigned long int)
  mp_bitcnt_t bits_;
  // actual number
  mpz_class value_;
  // GNU MP random algorithm
  gmp_randclass gmp_rand_alg_;

  //// private helper functions
  // set number of bits
  void bits(mp_bitcnt_t bits) { bits_ = bits; }
  // set value
  void value(mpz_class value) { value_ = value; }

  // set value_ to prime of ~k bits
  mpz_class generate_integer(mp_bitcnt_t k);

  //// friend non-member functions
  // stream extraction
  friend std::ostream& operator<<(std::ostream& os,
                                  const RandomInteger& random_integer);

  // stream insertion
  friend std::istream& operator>>(std::istream& is, RandomInteger& random_integer);
};
}
}

//// aliases
// namespace alias
namespace dgcrypto = DG::Crypto;
// type alias
using dgrint = DG::Crypto::RandomInteger;
