.\".TH CORRUPT 1
.\".SH NAME
.\"corrupt \- modify files by randomly changing bits
.\".SH SYNOPSIS
.\".B corrupt
.\"[\fB\-n\fR \fIBITS\fR]
.\"[\fB\-\-bits\fR \fIBITS\fR]
.\".IR file ...
.\".SH DESCRIPTION
.\".B corrupt
.\"modifies files by toggling a randomly chosen bit.
.\".SH OPTIONS
.\".TP
.\".BR \-n ", " \-\-bits =\fIBITS\fR
.\"Set the number of bits to modify.
.\"Default is one bit.
.TH GAUSS 1
.SH NAME
gauss \- generate a circuit from a truth-table algorithmically
.SH SYNOPSIS
gauss [options]
.SH DESCRIPTION
.TP
.B gauss
generates a circuit from a given truth-table using, optionally, a genetic algorithm or another search method.
.\".SH OPTIONS
