export UNAME=$(uname)
HOSTNAME=$(hostname)

# simple PS1
export PS1="\u@\H \W \$ ";

export EDITOR=vim         # for web devs
#export EDITOR=emacs      # for RMS
#export EDITOR=ed         # ED IS THE STANDARD TEXT EDITOR!
#export EDITOR=nano       # for nubs
#export EDITOR=sublime    # get out.
#export EDITOR=notepad++  # before it will work, run rm -rf *
export VISUAL=$EDITOR     # set $VISUAL to whatever you choose for $EDITOR

export PAGER=less
export LESS="-F -g -i -M -R -S -w -X -z-4"

export PATH=$HOME/local/$UNAME/bin:$PATH
export MANPATH=$HOME/local/$UNAME/share/man:$MANPATH

if [[ ${UNAME} == "SunOS" ]]; then
    # Solaris
    export PATH=$PATH
    # export CC=
    # export CXX=

    # include paths
    # export CPATH=:$CPATH
    # export CPLUS_INCLUDE_PATH=:$CPLUS_INCLUDE_PATH
    # export LD_LIBRARY_PATH=:$LD_LIBRARY_PATH

elif [[ ${UNAME} == "Linux" ]]; then
    # Linux
    export PATH=$PATH
    # export CC=
    # export CXX=

    # include paths
    # export CPATH=:$CPATH
    # export CPLUS_INCLUDE_PATH=:$CPLUS_INCLUDE_PATH
    # export LD_LIBRARY_PATH=:$LD_LIBRARY_PATH

    if [[ ${HOSTNAME} == "compute-linux1" ]]; then
        # Compute
        export PATH=$PATH
        export CC=
        export CXX=

        # include paths
        # export CPATH=:$CPATH
        # export CPLUS_INCLUDE_PATH=:$CPLUS_INCLUDE_PATH
        # export LD_LIBRARY_PATH=:$LD_LIBRARY_PATH

    elif [[ ${HOSTNAME} == "build" ]]; then
        # build
        export PATH=/usr/local/gcc4.9.2/bin:$PATH

        export MANPATH=/usr/local/gcc4.9.2/share/man:$MANPATH
        export LD_LIBRARY_PATH=/usr/local/gcc4.9.2/lib64:$LD_LIBRARY_PATH
        export LD_LIBRARY_PATH=$HOME/local/$UNAME/lib:$LD_LIBRARY_PATH
        export CPLUS_INCLUDE_PATH=$HOME/local/$UNAME/include:$CPLUS_INCLUDE_PATH

        # include paths
        # export CPATH=:$CPATH
        # export CPLUS_INCLUDE_PATH=:$CPLUS_INCLUDE_PATH

        if [ $(which ccache) ]; then
            export CC="ccache /usr/local/gcc4.9.2/bin/gcc -fdiagnostics-color=auto"
            export CXX="ccache /usr/local/gcc4.9.2/bin/g++ -fdiagnostics-color=auto"
        else
            export CC="/usr/local/gcc4.9.2/bin/gcc -fdiagnostics-color=auto"
            export CXX="/usr/local/gcc4.9.2/bin/g++ -fdiagnostics-color=auto"
        fi

        alias gcc-4.9.2="/usr/local/gcc4.9.2/bin/gcc -fdiagnostics-color=auto"
        alias g++-4.9.2="/usr/local/gcc4.9.2/bin/g++ -fdiagnostics-color=auto"

    fi
fi
